### ISSUE TITLE
Cannot use video

### ISSUE THREAD

**Issue by Pycwm** [opconty/face_detection_in_realtime#3]
Hi Conty,
I want to use the video,how can I do that?
Below is my issue.
Traceback (most recent call last):
  File "detect_realtime.py", line 25, in <module>
    if os.path.exists(args['video']):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by opconty** [comment]
HI Pycwm :
this is my running command, and it works fine,check your video path first:
$ python detect_realtime.py -v feifeili.mp4
Using TensorFlow backend.
2018-12-26 15:18:55.288366: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-26 15:18:55.291913: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-12-26 15:18:55.291948: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: laygin
2018-12-26 15:18:55.291979: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.130.0
2018-12-26 15:18:55.292001: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.130  Wed Mar 21 03:37:26 PDT 2018
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
"""
2018-12-26 15:18:55.292012: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.130.0
2018-12-26 15:18:55.292018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.130.0
[INFO] length of boxes0
[INFO] length of boxes0

Hope this helpful and have fun..

**Comment by Pycwm** [comment]
Hi Conty,
Thank you for your help!
I've solved the previous problem.I have other questions to ask you.
I find that the frame rate is low when only using CPU.
How to improve the speed of detection, and do you have the part of face recognition?
I'll wait for your answer.

**Comment by opconty** [comment]
you can try to resize your frame
